# Parameters related to building hipsparse
ARG base_image

FROM ${base_image}
LABEL maintainer="saad.rahim@amd"

# Copy the rpm package of hipsparse into the container from host
COPY *.rpm /tmp/

# Install the rpm package, and print out contents of expected changed locations
RUN dnf -y update && dnf install -y \
        /tmp/hipsparse-*.rpm \
    && dnf -y clean all \
    && printf "ls -la /etc/ld.so.conf.d/\n" && ls -la /etc/ld.so.conf.d/ \
    && printf "ls -la /opt/rocm/include\n" && ls -la /opt/rocm/include \
    && printf "ls -la /opt/rocm/lib64\n" && ls -la /opt/rocm/lib64 \
    && printf "ls -la /opt/rocm/lib64/cmake\n" && ls -la /opt/rocm/lib64/cmake \
    && printf "ls -la /opt/rocm/hipsparse/include\n" && ls -la /opt/rocm/hipsparse/include \
    && printf "ls -la /opt/rocm/hipsparse/lib64\n" && ls -la /opt/rocm/hipsparse/lib64