# Parameters related to building hipsparse
ARG base_image

FROM ${base_image}
LABEL maintainer="saad.rahim@amd"

# Copy the rpm package of hipsparse into the container from host
COPY *.rpm /tmp/

# Install the rpm package, and print out contents of expected changed locations
RUN dnf -y update && dnf install -y \
        /tmp/hipsparse-*.rpm \
    && dnf -y clean all \