# Parameters related to building hipSPARSE
ARG base_image

FROM ${base_image}
LABEL maintainer="rocsparse-maintainer@amd.com"

ARG user_uid
ARG REPO_RADEON=repo.radeon.com

# Install dependent packages
# Dependencies:
# * hcc-config.cmake: pkg-config
# * hipsparse-test: googletest
# * hipsparse-bench: libboost-program-options-dev
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends curl && \
    curl -sL http://${REPO_RADEON}/rocm/apt/debian/rocm.gpg.key | apt-key add - && \
    echo deb [arch=amd64] http://${REPO_RADEON}/rocm/apt/debian/ xenial main | tee /etc/apt/sources.list.d/rocm.list && \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    sudo \
    build-essential \
    ca-certificates \
    git \
    make \
    cmake \
    pkg-config \
    libnuma1 \
    libboost-program-options-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G sudo --shell /bin/bash jenkins && \
    mkdir -p /etc/sudoers.d/ && \
    echo '%sudo   ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd && \
    echo 'jenkins ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd
